repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.28
    hooks:
      - id: uv-lock
  # Apply version tag whenever version changes in pyproject.toml
  - repo: https://gitlab.com/snorkysnark/pyproject-auto-tag
    rev: v0.3.0
    hooks:
      - id: pyproject-auto-tag

default_install_hook_types: [pre-commit, post-commit]
