site_name: "ralsei"

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.tooltips

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            show_source: false
            members_order: source
            docstring_section_style: list
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.sqlalchemy.org/en/20/objects.inv
            - https://www.psycopg.org/psycopg3/docs/objects.inv

extra_css:
  - css/mkdocstrings.css

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference:
      - Tasks: api/tasks.md
      - Templates: api/templates.md
      - Map Functions: api/map_fn.md
      - Cli: api/cli.md
      - Connection: api/connection.md
      - Renderer: api/renderer.md
      - Cursor Factory: api/cursor_factory.md
      - Checks: api/checks.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

watch:
  - ralsei
