name: Setup
description: Checkout latest tag and install dependencies

runs:
  using: composite
  steps:
    - name: Fetch
      uses: actions/checkout@v4
      fetch-depth: 0
    - name: Find latest tag
      run: echo "LATEST_TAG=$(git tag | grep ^v | tail -n 1)" >> $GITHUB_ENV
    - name: Checkout latest tag
      run: git checkout $LATEST_TAG
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      run: pdm install
