name: publish

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Fetch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/find-latest-tag
      - name: Checkout latest tag
        run: git checkout $LATEST_TAG
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true
      - name: Install dependencies
        run: pdm install
      - name: Run Tests
        env:
          POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: pdm run pytest ./tests

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      # For github release
      contents: write
      # For PyPi trusted publishing
      id-token: write

    steps:
      - name: Fetch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/find-latest-tag
      - name: Checkout latest tag
        run: git checkout $LATEST_TAG
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true
      - name: Install dependencies
        run: pdm install
      - name: Build
        run: pdm build
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ env.LATEST_TAG }}
          prerelease: ${{ contains(env.LATEST_TAG, '.dev') }}
      - name: PyPi Release
        run: pdm publish
