name: publish-package

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      testpypi:
        description: Publish to TestPyPi, not PyPi
        required: true
        default: true
        type: boolean
      version:
        description: Override version
        type: string
        required: true

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/run-tests.yml

      - name: Install toml-cli
        run: pip install toml-cli
      - name: Set package version to ${{ inputs.version || github.ref_name }}
        run: toml set --toml-path pyproject.toml project.version ${{ inputs.version || github.ref_name }}

      - if: "!inputs.testpypi"
        name: Publish package distributions to PyPI
        run: pdm publish
      - if: inputs.testpypi
        name: Publish package distributions to TestPyPI
        run: pdm publish --repository testpypi
