name: publish

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Fetch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: snorkysnark/ralsei-py/.github/find-latest-tag@main
      - name: Checkout latest tag
        run: git checkout $LATEST_TAG
      - uses: snorkysnark/ralsei-py/.github/install-poetry-dependencies@main
      - name: Run Tests
        env:
          POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/postgres
          PYTHONPATH: .
        run: poetry run pytest ./tests

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      # For github release
      contents: write
      # For PyPi trusted publishing
      id-token: write

    steps:
      - name: Fetch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: snorkysnark/ralsei-py/.github/find-latest-tag@main
      - name: Checkout latest tag
        run: git checkout $LATEST_TAG
      - uses: snorkysnark/ralsei-py/.github/install-poetry-dependencies@main
      - name: Build
        run: poetry build
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ env.LATEST_TAG }}
          prerelease: ${{ contains(env.LATEST_TAG, '.dev') }}
      - name: PyPi Release
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: poetry publish --skip-existing

  docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: snorkysnark/ralsei-py/.github/find-latest-tag@main
      - name: Checkout latest tag
        run: git checkout $LATEST_TAG
      - uses: snorkysnark/ralsei-py/.github/install-poetry-dependencies@main
      - name: Build docs
        run: poetry run sphinx-build docs docs/_build
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build
