name: publish

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/find-latest-tag
      - name: Print version
        run: echo $LATEST_TAG
