name: run-tests

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/run-tests.yml
      - ralsei/**
      - tests/**
      - pyproject.toml
      - pdm.lock
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          update-python: true
          cache: true
      - name: Install dependencies
        run: pdm install
      - name: Run Tests
        run: pdm run pytest ./tests
        env:
          POSTGRES_URL: postgres://postgres:postgres@localhost:5432/postgres
